### ISSUE TITLE
.DS_STOREを含んでいる

### ISSUE THREAD

**Issue by mirror-kt** [unios103/unios103.github.io#2]

**Comment by mirror-kt** [comment]
`.DS_STORE`はmacOS独自の隠しファイルなのでWIndowsユーザーとかからしたらただの邪魔なゴミ
.gitignoreしときましょう

**Comment by unios103** [comment]
.gitignoreしました。ありがとう

**Comment by mirror-kt** [comment]
全部のサブディレクトリにあるはず…
プロジェクトルートのやつしか消えてないのでgit rmをそれぞれのサブディレクトリにしなきゃいけない

**Comment by unios103** [comment]
消しました！

**Comment by mirror-kt** [comment]
[これ](https://github.com/unios103/unios103.github.io/blob/master/img/.DS_Store)は…？

**Comment by unios103** [comment]
気づいてなかった、、ありがとう
